"""init schema

Revision ID: 2e8b67e17672
Revises: 5d153a8b143e
Create Date: 2025-10-04 15:59:44.256564

"""
from typing import Sequence, Union

# import sqlalchemy as sa
# from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e8b67e17672"
down_revision: Union[str, Sequence[str], None] = "5d153a8b143e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
