"""fix restaurant model

Revision ID: 73451feee1d8
Revises: d233a533e323
Create Date: 2025-10-06 12:56:10.585890

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "73451feee1d8"
down_revision: Union[str, Sequence[str], None] = "d233a533e323"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "menu_items", sa.Column("restaurant_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "menu_items", "restaurants", ["restaurant_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "menu_items", type_="foreignkey")
    op.drop_column("menu_items", "restaurant_id")
    # ### end Alembic commands ###
