"""create orders table

Revision ID: d233a533e323
Revises: cc7079ce170b
Create Date: 2025-10-06 11:24:12.032678

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d233a533e323"
down_revision: Union[str, Sequence[str], None] = "cc7079ce170b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("restaurant_tables")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "restaurant_tables",
        sa.Column(
            "id",
            sa.BIGINT(),
            sa.Identity(
                always=False,
                start=1,
                increment=1,
                minvalue=1,
                maxvalue=9223372036854775807,
                cycle=False,
                cache=1,
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "restaurant_id", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "table_number", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("restaurant_tables_pkey")),
    )
    # ### end Alembic commands ###
